### ISSUE TITLE
No module named 'telegram.ext'

### ISSUE THREAD

**Issue by mbnoimi** [JungDev/django-telegrambot#41]
Hi,

Whenever I try to run any project I get this error message:
```
  File "/home/laptop/.pyenv/versions/django-telegrambot/lib/python3.6/site-packages/django_telegrambot/apps.py", line 9, in <module>
    from telegram.ext import Dispatcher
ModuleNotFoundError: No module named 'telegram.ext'
```
Does `django-telegrambot` is outdated Or my settings are incorrect?

**My Settings:**
```
$ python --version
Python 3.6.9

$ pip list
Package             Version
------------------- ---------
asgiref             3.2.10
certifi             2020.6.20
cffi                1.14.0
cryptography        2.9.2
decorator           4.4.2
Django              3.0.7
django-telegrambot  1.0.1
djangorestframework 3.3.2
future              0.18.2
pip                 20.1.1
pkg-resources       0.0.0
pycparser           2.20
python-telegram-bot 3.2.0
pytz                2020.1
setuptools          39.0.1
six                 1.15.0
sqlparse            0.3.1
tornado             6.0.4

$ python manage.py runserver
Watching for file changes with StatReloader
INFO 2020-06-22 07:06:08,863 autoreload Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/laptop/.pyenv/versions/django-telegrambot/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/laptop/.pyenv/versions/django-telegrambot/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/laptop/.pyenv/versions/django-telegrambot/lib/python3.6/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/home/laptop/.pyenv/versions/django-telegrambot/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/home/laptop/.pyenv/versions/django-telegrambot/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/laptop/.pyenv/versions/django-telegrambot/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/laptop/.pyenv/versions/django-telegrambot/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/laptop/.pyenv/versions/django-telegrambot/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/laptop/.pyenv/versions/django-telegrambot/lib/python3.6/site-packages/django_telegrambot/apps.py", line 9, in <module>
    from telegram.ext import Dispatcher
ModuleNotFoundError: No module named 'telegram.ext'
```

**Comment by lukruh** [comment]
``telegram.ext` should be part of `python-telegram-bot`. The latest version of python-telegram-bot is 12.8 you are on 3.x? That looks really outdated.. 
You should try to update ptb first, maybe to something like v11.x, because v12 breaks some compabilities to django-telegrambot 1.0.1 if I remember right.

**Comment by mbnoimi** [comment]
> `telegram.ext` should be part of `python-telegram-bot`. The latest version of python-telegram-bot is 12.8 you are on 3.x? That looks really outdated..
> You should try to update ptb first, maybe to something like v11.x, because v12 breaks some compabilities to django-telegrambot 1.0.1 if I remember right.

Thanks a lot, This is absolutely correct.

**Comment by lukruh** [comment]
There are some minor issues if you use the latest Django and PTB modules, check out the PR here or my fork, if you want to fix them..

**Comment by mbnoimi** [comment]
I did face any problem by using the following packages:
```sh
$ pip list
Package             Version  
------------------- ---------
asgiref             3.2.10   
astroid             2.4.2    
certifi             2020.6.20
cffi                1.14.0   
cryptography        2.9.2    
decorator           4.4.2    
Django              3.0.7    
django-telegrambot  1.0.1    
isort               4.3.21   
lazy-object-proxy   1.4.3    
mccabe              0.6.1    
pip                 19.2.3   
pycparser           2.20     
pylint              2.5.3    
python-telegram-bot 12.8     
pytz                2020.1   
setuptools          41.2.0   
six                 1.15.0   
sqlparse            0.3.1    
toml                0.10.1   
tornado             6.0.4    
wrapt               1.12.1   
```
@lukruh May you please make a pull request for fixing them

**Comment by lukruh** [comment]
I'm on vacations right now and I think this repo is not activly maintained so a new PR wouldnt be accepted anyways. But until than you can checkout my fork of this repo, where I fixed all issues with django3 and latest ptb versions I found.. feel free to open issues if encounter some..
https://github.com/telebotter/django-telegrambot

**Comment by mbnoimi** [comment]
Thanks a lot

**Comment by lukruh** [comment]
I guess you have to uninstall the old version of django-telegrambot first, to avoid naming conflicts. To check if you are on the right version you can try
```
import django-telegrambot
print(django-telegrambot.__version__)
```
should be 1.0.2

**Comment by mbnoimi** [comment]
No need for this because I run `pip uninstall django-telegrambot` so `django_telegrambot 1.0.2` works fine.

Thanks anyway.
