### ISSUE TITLE
AttributeError: 'list' object has no attribute 'data_filter'

### ISSUE THREAD

**Issue by alibaltschun** [JungDev/django-telegrambot#49]
```
 python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/baltschun/opt/anaconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/baltschun/opt/anaconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django_telegrambot/apps.py", line 230, in ready
    if module_exists(module_name, 'main', True):
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/django_telegrambot/apps.py", line 216, in module_exists
    getattr(m, method_name)()
  File "/Users/baltschun/project/ananas/private_web/app/app_attendance/telegrambot.py", line 45, in main
    dp.add_handler(MessageHandler([Filters.text], echo))
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/telegram/ext/messagehandler.py", line 150, in __init__
    self.filters = Filters.update & filters
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/telegram/ext/filters.py", line 121, in __and__
    return MergedFilter(self, and_filter=other)
  File "/Users/baltschun/project/ananas/venv_attendance/lib/python3.8/site-packages/telegram/ext/filters.py", line 255, in __init__
    and self.and_filter.data_filter
AttributeError: 'list' object has no attribute 'data_filter'
```

**Comment by hypy13** [comment]
i have this problem too
did you fix it?
